version: "3.3"

services:
  webrtc-sip-gw:
    container_name: webrtc-sip-gw
    image: ghcr.io/florian-h05/webrtc-sip-gw
    restart: always
    network_mode: host
    volumes:
     - ./ssl/sipgw.key:/etc/ssl/privkey.pem:ro # Can be left out when TLS is disabled
     - ./ssl/sipgw.crt:/etc/ssl/fullchain.pem:ro # Can be left out when TLS is disabled
    environment:
     - TLS_DISABLE=false # Optional, defaults to false
